services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: luwa
    ports:
      - "5432:5432"
    # volumes:
    #   - luwa_db:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://admin:admin@db:5432/luwa?sslmode=disable"

# volumes:
#   luwa_db: {}